M48
; DRILL file {KiCad 8.0.2} date 2024-08-15T23:43:10-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-15T23:43:10-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1969
%
G90
G05
T1
X1.5748Y2.0236
T2
X0.1969Y3.7402
X0.1969Y0.1969
X2.5591Y3.7402
X2.5591Y0.1969
M30
